name = "ScheduleMeetings"
uuid = "18647eb5-d111-4953-ac7e-c27d8fc5d0b4"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
